package model;
// Generated 29 sept. 2015 16:10:39 by Hibernate Tools 4.3.1

import java.util.List;
import org.hibernate.Session;
import org.hibernate.criterion.Restrictions;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;




/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     
     @NotEmpty
     private String nom;
     
     @NotEmpty
     private String prenom;
     
     @NotEmpty
     @Email
     private String email;
     
     @NotEmpty
     private String pwd;
     
     @NotEmpty
     private String confirmpwd;
     
     private int statut;

    public User() {
    }

    public User(String nom, String prenom, String email, String pwd, String confirmpwd, int statut) {
       this.nom = nom;
       this.prenom = prenom;
       this.email = email;
       this.pwd = pwd;
       this.confirmpwd = confirmpwd;
       this.statut = statut;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPwd() {
        return this.pwd;
    }
    
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }
    public String getConfirmpwd() {
        return this.confirmpwd;
    }
    
    public void setConfirmpwd(String confirmpwd) {
        this.confirmpwd = confirmpwd;
    }
    
     public int getStatut() {
        return this.statut;
    }
    
    public void setStatut(int statut) {
        this.statut = statut;
    }

 public User getUserFromSignupToken(String token)  {
         List users = HibernateUtil.getSessionFactory().openSession().createCriteria(User.class).add(Restrictions.eq("confirmpwd", token)).list();
   // List users = getSession().createCriteria(User.class).add(Restrictions.eq("emailConfirmToken", token)).list();
   
   
        return (User) users.get(0);
    
}


}


